winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
  - name: System
  - name: Microsoft-Windows-TerminalServices-RDPClient/Operational
    event_id: 23,24,25,1102
    ignore_older: 72h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Admin
    event_id: 23,24,25,1102
    ignore_older: 72h
  - name: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    event_id: 23,24,25,1102
    ignore_older: 72h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurity
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 72h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurityVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 72h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 72h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/FirewallVerbose
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 72h
  - name: Microsoft-Windows-Windows Firewall With Advanced Security/Network Isolation Operational
    event_id: 2004,2005,2006,2033,2009
    ignore_older: 72h
  - name: "Microsoft-Windows-WindowsUpdateClient/Operational"
    event_id: 20,24,25,31,34,35
    ignore_older: 72h
  - name: "Microsoft-Windows-NTLM/Operational"
    ignore_older: 72h
  - name: Microsoft-AzureADPasswordProtection-DCAgent/Admin
  - name: Microsoft-AzureADPasswordProtection-DCAgent/Operational
  - name: Microsoft-AzureADPasswordProtection-ProxyService/Admin
  - name: Microsoft-AzureADPasswordProtection-ProxyService/Operational
  - name: "Directory Service"
  - name: "DFS Replication"
tags: ["DC"]

output.logstash:
  hosts: ["logstashserver:5044"]

